// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiHFf8xrg_Ccisrmtd8Qol7Z8SEITggg',
    appId: '1:437347114454:web:dad9327e0ae62c4f14d877',
    messagingSenderId: '437347114454',
    projectId: 'farmtrack-fe711',
    authDomain: 'farmtrack-fe711.firebaseapp.com',
    storageBucket: 'farmtrack-fe711.firebasestorage.app',
    measurementId: 'G-44SS8FSQTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrODsVw5bcdcmVjB6rQy_sWWz2TJRzq0',
    appId: '1:437347114454:android:8118726ddc4a40b214d877',
    messagingSenderId: '437347114454',
    projectId: 'farmtrack-fe711',
    storageBucket: 'farmtrack-fe711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxs9PzfJYXcysQQljSFPV_VPViTcr-AE',
    appId: '1:437347114454:ios:12723f344f3ce7f214d877',
    messagingSenderId: '437347114454',
    projectId: 'farmtrack-fe711',
    storageBucket: 'farmtrack-fe711.firebasestorage.app',
    androidClientId: '437347114454-776q0kr0og7kbpvm6c8v8pk9pke0psfe.apps.googleusercontent.com',
    iosClientId: '437347114454-0bn60q6mu8nk4rclie9vsmkvp0bi3n8h.apps.googleusercontent.com',
    iosBundleId: 'com.farmtrack.farmerTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeiHFf8xrg_Ccisrmtd8Qol7Z8SEITggg',
    appId: '1:437347114454:web:dafc0a18b1305f6514d877',
    messagingSenderId: '437347114454',
    projectId: 'farmtrack-fe711',
    authDomain: 'farmtrack-fe711.firebaseapp.com',
    storageBucket: 'farmtrack-fe711.firebasestorage.app',
    measurementId: 'G-2LY1BDDFTY',
  );

}